# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='用户名', max_length=100)),
                ('password', models.CharField(help_text='密码', max_length=255)),
                ('salt', models.IntegerField(help_text='盐值(用于加强MD5加密强度)', max_length=3)),
                ('tel', models.CharField(help_text='分机号', max_length=11)),
                ('status', models.IntegerField(help_text='状态', max_length=3)),
                ('last_login_ip', models.CharField(help_text='最后登录IP', max_length=100)),
                ('last_login_time', models.IntegerField(default=0, help_text='最后登录时间', max_length=11)),
                ('expire_time', models.IntegerField(default=0, help_text='过期时间', max_length=11)),
                ('create_time', models.IntegerField(help_text='创建时间', max_length=11)),
                ('update_time', models.IntegerField(help_text='更新时间', max_length=11)),
                ('permission', models.NullBooleanField(default=0, help_text='管理员权限(0:普通,1:超级)', max_length=2)),
            ],
        ),
    ]
