# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='create_time',
            field=models.IntegerField(help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='expire_time',
            field=models.IntegerField(default=0, help_text='过期时间'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='last_login_time',
            field=models.IntegerField(default=0, help_text='最后登录时间'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='salt',
            field=models.IntegerField(help_text='盐值(用于加强MD5加密强度)'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='status',
            field=models.IntegerField(help_text='状态'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='update_time',
            field=models.IntegerField(help_text='更新时间'),
        ),
    ]
