# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170316_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('author', models.CharField(help_text='作者名', max_length=255)),
                ('status', models.IntegerField(help_text='状态')),
                ('createdby', models.CharField(help_text='创建者', max_length=255)),
                ('create_time', models.IntegerField(help_text='创建时间')),
                ('update_time', models.IntegerField(help_text='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('banner_title', models.CharField(default=0, help_text='banner图名称', max_length=255)),
                ('banner_admin', models.IntegerField(default=0, help_text='发布管理员ID')),
                ('update_admin', models.IntegerField(default=0, help_text='更新管理员ID')),
                ('status', models.IntegerField(default=0, help_text='状态')),
                ('origin_image_name', models.CharField(help_text='banner图片原名', max_length=255)),
                ('source_image', models.CharField(help_text='banner图片原图', max_length=255)),
                ('create_time', models.IntegerField(help_text='创建时间')),
                ('update_time', models.IntegerField(help_text='更新时间')),
                ('start_time', models.IntegerField(help_text='banner开始时间')),
                ('end_time', models.IntegerField(help_text='banner结束时间')),
                ('show_flag', models.IntegerField(default=0, help_text='公开标识')),
                ('url', models.CharField(help_text='banner图片的URL链接', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('event_author', models.IntegerField(default=0, help_text='发布作者ID')),
                ('event_admin', models.IntegerField(default=0, help_text='发布管理员ID')),
                ('update_admin', models.IntegerField(default=0, help_text='更新管理员ID')),
                ('event_content', models.TextField(help_text='活动内容')),
                ('event_title', models.CharField(help_text='活动标题', max_length=255)),
                ('status', models.IntegerField(default=0, help_text='状态')),
                ('origin_image_name', models.CharField(help_text='活动详情页图片原名', max_length=255)),
                ('origin_title_image_name', models.CharField(help_text='首页活动图片原名', max_length=255)),
                ('source_image', models.CharField(help_text='活动详情页图片原图', max_length=255)),
                ('source_title_image', models.CharField(help_text='首页活动图片原图', max_length=255)),
                ('create_time', models.IntegerField(help_text='创建时间')),
                ('update_time', models.IntegerField(help_text='更新时间')),
                ('start_time', models.IntegerField(help_text='活动开始时间')),
                ('end_time', models.IntegerField(help_text='活动结束时间')),
                ('show_flag', models.IntegerField(default=0, help_text='公开标识')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('create_admin_id', models.IntegerField(help_text='创建管理员ID')),
                ('update_admin_id', models.IntegerField(help_text='更新管理员ID')),
                ('status', models.IntegerField(help_text='状态')),
                ('useless', models.IntegerField(default=0, help_text='废弃标识')),
                ('create_time', models.IntegerField(help_text='创建时间')),
                ('update_time', models.IntegerField(help_text='更新时间')),
                ('start_time', models.IntegerField(default=0, help_text='维护开始时间')),
                ('end_time', models.IntegerField(default=0, help_text='维护结束时间')),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField(help_text='管理员ID')),
                ('create_time', models.IntegerField(help_text='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('post_author', models.IntegerField(default=0, help_text='发布作者ID')),
                ('post_admin', models.IntegerField(default=0, help_text='发布管理员ID')),
                ('update_admin', models.IntegerField(default=0, help_text='更新管理员ID')),
                ('post_content', models.TextField(help_text='新闻内容')),
                ('post_title', models.CharField(help_text='新闻标题', max_length=255)),
                ('status', models.IntegerField(default=0, help_text='状态')),
                ('tag_id', models.IntegerField(default=0, help_text='标签ID')),
                ('origin_image_name', models.CharField(help_text='新闻详情页图片原名', max_length=255)),
                ('origin_title_image_name', models.CharField(help_text='首页新闻图片原名', max_length=255)),
                ('source_image', models.CharField(help_text='新闻详情页图片原图', max_length=255)),
                ('source_title_image', models.CharField(help_text='首页新闻图片原图', max_length=255)),
                ('create_time', models.IntegerField(help_text='创建时间')),
                ('update_time', models.IntegerField(help_text='更新时间')),
                ('start_time', models.IntegerField(help_text='新闻开始时间')),
                ('end_time', models.IntegerField(help_text='新闻结束时间')),
                ('show_flag', models.IntegerField(default=0, help_text='公开标识')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('tag_name', models.CharField(help_text='标签名', max_length=255)),
                ('status', models.IntegerField(help_text='状态')),
                ('createdby', models.CharField(help_text='创建者', max_length=255)),
                ('create_time', models.IntegerField(help_text='创建时间')),
                ('update_time', models.IntegerField(help_text='更新时间')),
            ],
        ),
    ]
