# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_author_banners_events_maintenance_online_posts_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.TextField(help_text='密码', max_length=255),
        ),
    ]
