# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20170322_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
